spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/receitasdb
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

jwt:
  key:
    public: classpath:app.pub
    private: classpath:app.key
