spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/receitasdb
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver